### ISSUE TITLE
Error when sending email / when viewing Email

### ISSUE THREAD

**Issue by WahlFisch91** [AndreasNick/OTPEdit#5]
Hi,

I am facing problems when sending emails via the OTP-Explorer...
![grafik](https://user-images.githubusercontent.com/38093968/183342442-681c5c28-d3a5-4486-9b1c-9e1f85607060.png)

i am sending the emails via the local exchange server (smtp).

at the end, the email is delivered - but when i view the mail in Outlook 2016, the QR Code is only showing a "X" - see screenshot

![grafik](https://user-images.githubusercontent.com/38093968/183343116-aa90e62b-34c6-4cfe-b275-353cbbfa4792.png)

Does anyone have the same problems?

**Comment by AndreasNick** [comment]
The steroids were used to create the EXE. In fact, a command has crept into line 791 that should end up in the console. The e-mail should be sent anyway (OTPEdit.ps1)! By the way, you can also use the PowerShell instead of the exe. That Outlook displays a picture is often standard. I have therefore embedded the QR code. But does "right mouse button" and "download picture" work? 

![image](https://user-images.githubusercontent.com/38461841/183351671-819d440f-276c-44b5-836c-1a15af8d404b.png)

**Comment by WahlFisch91** [comment]
okay - so if i understand correctly - the error message could be ignored?

regarding email:
I do not have the option to download pictures....looks like an outlook issue....on my iphone i can see the qr code without any problems....

![grafik](https://user-images.githubusercontent.com/38093968/183361621-d58c94b5-5b1c-446d-87f6-7a960d9626c9.png)

**Comment by WahlFisch91** [comment]
In OWA i can see the QR Code as well :(
Looks like Outlook is blocking embedded Images....i was reading something about base64 image format

https://www.caniemail.com/features/image-base64/

i am wondering that i am the only one, who is facing this problem :)

**Comment by AndreasNick** [comment]
Unfortunately, I can't tell you. But I know of several customers of mine who also send emails with it and I tested it with my own Outlook back then. Maybe a security setting on the Exchange Server? Trojans are often Base64 encoded as well. But for this reason I have built the script that sends the email independently. At that time I had problems to send an email with attachment with PowerShell. This is probably just a time issue. You could customize the script and convert the Base64 part to a PNG and send it as attachment. https://github.com/AndreasNick/OTPEdit/blob/master/Send-QRCodeEmail.ps1 
![image](https://user-images.githubusercontent.com/38461841/183491866-93bf0999-a840-41f8-bf8a-91d0de1e3271.png)

Maybe a help: https://stackoverflow.com/questions/3997303/how-to-attach-a-file-to-an-email-with-powershell

**Comment by WahlFisch91** [comment]
The Problem could not be on exchange server side because it works on iphone and OWA :(

But forget about it - i have rewritten your script (Send-QRCodeEmail.ps1).....
i am converting the base64 image into a png file and attach it to the email...works like it should :)

It is a little workaround, but i am happy with it.

See Powershell Script attached...
[Send-QRCodeEmail.zip](https://github.com/AndreasNick/OTPEdit/files/9287771/Send-QRCodeEmail.zip)
